export const arrayOfLocation = {
  region: [
    "Bagmati Province",
    "Gandaki Province",
    "Karnali Province",
    "Lumbini Province",
    "Province 1",
    "Province 2",
    "Sudurpashchim Province",
  ],
  city: [
    {
      id: "Bagmati Province",
      locations: [
        "Banepa",
        "Bhaktapur",
        "Bharatpur",
        "Hetauda",
        "Kathmandu Metro 10 - New Baneshwor Area",
        "Kathmandu Metro 11 - Maitighar Area",
        "Kathmandu Metro 12 - Teku Area",
        "Kathmandu Metro 13 - Kalimati Area",
        "Kathmandu Metro 14 - Kuleshwor Area",
        "Kathmandu Metro 15 - Swayambhu Area",
        "Kathmandu Metro 16 - Nayabazar Area",
        "Kathmandu Metro 17 - Chhetrapati Area",
        "Kathmandu Metro 18 - Raktakali Area",
        "Kathmandu Metro 19 - Hanumandhoka Area",
        "Kathmandu Metro 1 - Naxal Area",
        "Kathmandu Metro 20 - Marutol Area",
        "Kathmandu Metro 21 - Lagantole Area",
        "Kathmandu Metro 22 - Newroad Area",
        "Kathmandu Metro 23 - Basantapur Area",
        "Kathmandu Metro 24 - Indrachowk Area",
        "Kathmandu Metro 25 - Ason Area",
        "Kathmandu Metro 26 - Samakhusi Area",
        "Kathmandu Metro 26 - Thamel Area",
        "Kathmandu Metro 27 - Bhotahiti Area",
        "Kathmandu Metro 28 - Bagbazar Area",
        "Kathmandu Metro 28 - Kamaladi Area",
        "Kathmandu Metro 29 - Anamnagar Area",
        "Kathmandu Metro 29 - Putalisadak Area",
        "Kathmandu Metro 2 - Lazimpat Area",
        "Kathmandu Metro 30 - Maitidevi Area",
        "Kathmandu Metro 31 - Min Bhawan Area",
        "Kathmandu Metro 32 - Koteshwor Area",
        "Kathmandu Metro 32 - Tinkune Area",
        "Kathmandu Metro 3 - Baluwatar Area",
        "Kathmandu Metro 3 - Maharajgunj Area",
        "Kathmandu Metro 4 - Bishalnagar Area",
        "Kathmandu Metro 5 - Tangal Area",
        "Kathmandu Metro 7 - Chabahil Area",
        "Kathmandu Metro 8 - Gaushala Area",
        "Kathmandu Metro 9 - Sinamangal Area",
        "Kathmandu Outside Ring Road",
        "Khairehani",
        "Lalitpur Inside Ring Road",
        "Lalitpur Outside Ring Road",
        "Narayanghat",
        "Rapti",
        "Ratnanagar",
      ],
    },
    {
      id: "Gandaki Province",
      locations: ["Damauli", "Gaindakot", "Kawasoti", "Lekhnath", "Pokhara"],
    },
    { id: "Karnali Province", locations: ["Birendranagar - Surkhet"] },
    {
      id: "Lumbini Province",
      locations: [
        "Butwal",
        "Dang - Ghorahi",
        "Dang - Tulsipur",
        "Devdaha",
        "Lumbini Sanskriti",
        "Nepalgunj",
        "Ramgram",
        "Sainamaina",
        "Sidarthanagar - Bhairahawa",
        "Sunwal",
        "Taulihawa - Kapilvastu",
        "Tilotama",
      ],
    },
    {
      id: "Province 1",
      locations: [
        "Bhadrapur",
        "Biratnagar",
        "Birtamod",
        "Chandragadi",
        "Damak",
        "Dharan",
        "Itahari",
        "Kakarbhitta",
        "Urlabari",
      ],
    },
    {
      id: "Province 2",
      locations: [
        "Bardibas",
        "Birgunj",
        "Chhireswarnath",
        "Jaleswor",
        "Janakpur",
        "Jeetpur - Simara",
        "Kalaiya",
        "Lahan",
      ],
    },
    {
      id: "Sudurpashchim Province",
      locations: ["Bhimdatta-Mahendranagar", "Dhangadhi"],
    },
  ],
  area: [],
  address: [],
};
